stages:
    - test

newman_tests:
    stage: test
    image:
        name: postman/newman
        entrypoint: [""]
    script:
        - newman --version
        - npm i newman-reporter-html
        - newman run collections/spacexapi.postman_collection.json -e environments/spacexapi.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export report.html